<section id="about_us">
    <div class="about_us_container">
        <div class="about_us_container__column">
            <h1>O <span>nas</span></h1>
            <p>Spark Promotions to <a href="http://">agencja reklamowa</a>, specjalizująca się w sprzedaży gadżetów promocyjnych dla firm i instytucji. Realizujemy <strong>zamówienia katalogowe</strong> oraz <strong>zlecenia importowe</strong>. Sukcesywnie powiększamy nasz asortyment o oferty renomowanych dostawców. Na życzenie klienta projektujemy gadżety od podstaw i czuwamy nad procesem ich produkcji.Towar, który proponujemy naszym odbiorcom znakujemy w profesjonalnej drukarni, dobierając najlepszą do tego metodę.<br><i>Przypominamy, że ceny podane na stronie są cenami netto oraz nie zawierają kosztów znakowania i transportu.</i></p>
            <h1>Nie masz pomysłu na <span>skuteczną reklamę</span>? Postaw na <span>gadżety reklamowe</span> i zapadnij w pamięci klientów!</h1>
            <p>Klient to największe dobro każdego przedsiębiorcy. Dotarcie do szerokiego grona odbiorców to gwarancja odniesienia biznesowego sukcesu. W dobie wzmożonego rozwoju gospodarki i stale rosnącej konkurencji rozreklamowanie swojej marki jest jednak prawdziwą sztuką. Wybierając formę reklamy musimy nie tylko wyróżnić swoją ofertę na tle innych, ale także utkwić w pamięci wymagających klientów.</p>
            <p>Dlatego nowoczesny marketing ma na celu zwiększenie sprzedaży i zbudowanie pozytywnego wizerunku firmy, z którym klienci będą chcieli się utożsamiać. Jak pokazują badania najlepszym sposobem tworzenia rozpoznawalności marki są gadżety reklamowe.</p>
        </div>
        <div class="about_us_container__column second">
            <h1>Buduj świadomość swojej marki poprzez <span>gustowne upominki reklamowe</span></h1>
            <p>SPARK-PROMOTIONS skupia się na produkcji i imporcie gadżetów reklamowych dla firm . Nasi klienci stanowią dla nas największe dobro, dlatego z myślą o nich stale ulepszamy i powiększamy naszą ofertę. Wiemy w jak różnorodnych branżach działają i dlatego do każdego zlecenia podchodzimy w sposób indywidualny. Oferowane przez nas produkty są tworzone z najwyższą starannością tak, by zadowolić nawet najbardziej wymagających klientów.</p>
            <p>Każda firma pragnąca budować rozpoznawalność swojej marki znajdzie na naszej stronie spersonalizowane produkty m. in. długopisy reklamowe, kubki z nadrukiem, koszulki, bluzy, pamięć USB, papeterie i wiele innych. Inwestując w gadżety reklamowe mają Państwo pewność uzyskania szybkiego wzrostu sprzedaży i zwiększenia rozpoznawalności swojej marki. Nasze produkty są produkowane zgodnie z Państwa oczekiwaniami.</p>
            <p>Lata doświadczenia i stosowanie najwyższej jakości elementów sprawiły, że wiemy jak korzystnie rozreklamować firmy z różnych branż. Ilość zadowolonych klientów jest potwierdzeniem, że oferowane przez nas artykuły promocyjne docierają do szerokiej rzeszy potencjalnych nabywców. Masz problem z doborem odpowiednich gadżetów? Nasi konsultanci służą swoją pomocą! Dlatego nie czekaj i zainwestuj w rozwój swojej marki, a spektakularne efekty pojawią się szybciej niż myślisz. Pamiętaj, że gadżety promocyjne od SPARK-PROMOTIONS to miły upominek, który zostanie zapamiętany na długo!</p>
        </div>
    </div>
</section>